workflows:
  ios_testflight:
    name: iOS → TestFlight (manual cert)
    integrations:
      app_store_connect: Aug30-Codemagic-API-Key   # <-- use YOUR integration name exactly
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yalpertem.simpleweather
      vars:
        BUNDLE_ID: com.yalpertem.simpleweather
        APP_STORE_APP_ID: 6751532679

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Install uploaded certificates & fetch provisioning profiles
        script: |
          set -e
          keychain initialize
          # Installs ALL certificates you uploaded in Codemagic UI (including your new .p12)
          keychain add-certificates
          # Create/fetch an App Store profile for the exact bundle id
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          # Apply those profiles to the Xcode project
          xcode-project use-profiles
          # (Optional) print for debugging
          xcode-project print-signing-settings

      - name: Set build number from Codemagic
        script: |
          BUILD_NUMBER=${CM_BUILD_ID:-1}
          /usr/libexec/PlistBuddy -c "Set CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist

      - name: Build iOS IPA
        script: |
          flutter clean
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
